# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'primo.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(789, 449)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(340, 30, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEditNumero1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNumero1.setGeometry(QtCore.QRect(150, 160, 461, 41))
        self.lineEditNumero1.setObjectName("lineEditNumero1")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 70, 631, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.labelResultado = QtWidgets.QLabel(self.centralwidget)
        self.labelResultado.setGeometry(QtCore.QRect(120, 240, 551, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.labelResultado.setFont(font)
        self.labelResultado.setObjectName("labelResultado")
        self.pushButtonEnviar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonEnviar.setGeometry(QtCore.QRect(340, 340, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonEnviar.setFont(font)
        self.pushButtonEnviar.setObjectName("pushButtonEnviar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 789, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Primo"))
        self.label_3.setText(_translate("MainWindow", "Digite um númeor para saber se ele é primo ou não:"))
        self.labelResultado.setText(_translate("MainWindow", "Resultado:"))
        self.pushButtonEnviar.setText(_translate("MainWindow", "Enviar"))
