# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mediaAritmeticaDinamica.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelPergunta = QtWidgets.QLabel(self.centralwidget)
        self.labelPergunta.setGeometry(QtCore.QRect(70, 140, 291, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.labelPergunta.setFont(font)
        self.labelPergunta.setWordWrap(True)
        self.labelPergunta.setObjectName("labelPergunta")
        self.pushButtonEnviar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonEnviar.setGeometry(QtCore.QRect(460, 240, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonEnviar.setFont(font)
        self.pushButtonEnviar.setObjectName("pushButtonEnviar")
        self.lineEditInput = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditInput.setGeometry(QtCore.QRect(390, 170, 311, 41))
        self.lineEditInput.setObjectName("lineEditInput")
        self.labelResultado = QtWidgets.QLabel(self.centralwidget)
        self.labelResultado.setGeometry(QtCore.QRect(80, 320, 631, 181))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.labelResultado.setFont(font)
        self.labelResultado.setText("")
        self.labelResultado.setAlignment(QtCore.Qt.AlignCenter)
        self.labelResultado.setWordWrap(True)
        self.labelResultado.setObjectName("labelResultado")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(290, 30, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelPergunta.setText(_translate("MainWindow", "Digite o número de notas a serem inseridas:"))
        self.pushButtonEnviar.setText(_translate("MainWindow", "Enviar"))
        self.pushButtonEnviar.setShortcut(_translate("MainWindow", "Return"))
        self.label_3.setText(_translate("MainWindow", "Média Aritmética"))
