# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maiorNumero.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 30, 531, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEditNum3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNum3.setGeometry(QtCore.QRect(540, 150, 211, 41))
        self.lineEditNum3.setObjectName("lineEditNum3")
        self.lineEditNum1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNum1.setGeometry(QtCore.QRect(40, 150, 211, 41))
        self.lineEditNum1.setObjectName("lineEditNum1")
        self.lineEditNum2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNum2.setGeometry(QtCore.QRect(290, 150, 211, 41))
        self.lineEditNum2.setObjectName("lineEditNum2")
        self.labelResultado = QtWidgets.QLabel(self.centralwidget)
        self.labelResultado.setGeometry(QtCore.QRect(200, 220, 411, 141))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.labelResultado.setFont(font)
        self.labelResultado.setWordWrap(True)
        self.labelResultado.setObjectName("labelResultado")
        self.pushButtonEnviar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonEnviar.setGeometry(QtCore.QRect(300, 410, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButtonEnviar.setFont(font)
        self.pushButtonEnviar.setObjectName("pushButtonEnviar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Informe 3 números para saber qual é maior"))
        self.labelResultado.setText(_translate("MainWindow", "Resultado:"))
        self.pushButtonEnviar.setText(_translate("MainWindow", "Enviar"))
