# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'soma.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(587, 454)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 20, 91, 51))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 120, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEditNumero1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNumero1.setGeometry(QtCore.QRect(270, 130, 281, 31))
        self.lineEditNumero1.setObjectName("lineEditNumero1")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 180, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEditNumero2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNumero2.setGeometry(QtCore.QRect(270, 190, 281, 31))
        self.lineEditNumero2.setObjectName("lineEditNumero2")
        self.labelResulatdo = QtWidgets.QLabel(self.centralwidget)
        self.labelResulatdo.setGeometry(QtCore.QRect(30, 320, 521, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelResulatdo.setFont(font)
        self.labelResulatdo.setObjectName("labelResulatdo")
        self.pushButtonSomar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSomar.setGeometry(QtCore.QRect(224, 250, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButtonSomar.setFont(font)
        self.pushButtonSomar.setObjectName("pushButtonSomar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 587, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Soma"))
        self.label_2.setText(_translate("MainWindow", "Digite o primeiro número:"))
        self.label_3.setText(_translate("MainWindow", "Digite o segundo número:"))
        self.labelResulatdo.setText(_translate("MainWindow", "Resultado:"))
        self.pushButtonSomar.setText(_translate("MainWindow", "Somar"))
