# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mediaAritmetica.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(587, 454)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEditNumero2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNumero2.setGeometry(QtCore.QRect(280, 180, 281, 31))
        self.lineEditNumero2.setObjectName("lineEditNumero2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 170, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.labelResulatdo = QtWidgets.QLabel(self.centralwidget)
        self.labelResulatdo.setGeometry(QtCore.QRect(30, 350, 531, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelResulatdo.setFont(font)
        self.labelResulatdo.setObjectName("labelResulatdo")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 10, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 110, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEditNumero1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNumero1.setGeometry(QtCore.QRect(280, 120, 281, 31))
        self.lineEditNumero1.setObjectName("lineEditNumero1")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 230, 241, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEditNumero3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditNumero3.setGeometry(QtCore.QRect(280, 240, 281, 31))
        self.lineEditNumero3.setText("")
        self.lineEditNumero3.setObjectName("lineEditNumero3")
        self.pushButtonEnviar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonEnviar.setGeometry(QtCore.QRect(230, 280, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButtonEnviar.setFont(font)
        self.pushButtonEnviar.setObjectName("pushButtonEnviar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 587, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Digite o segundo número:"))
        self.labelResulatdo.setText(_translate("MainWindow", "Resultado"))
        self.label.setText(_translate("MainWindow", "Média Aritmética"))
        self.label_2.setText(_translate("MainWindow", "Digite o primeiro número:"))
        self.label_4.setText(_translate("MainWindow", "Digite o terceiro número:"))
        self.pushButtonEnviar.setText(_translate("MainWindow", "Enviar"))
